<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="3" total="4" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[{"id":901,"category":{"id":0,"name":"string"},"name":"doggie-901","photoUrls":["string"],"tags":[{"id":0,"name":"string"}],"status":"available"}]]>
    </line>
  </reporter-output>
  <suite started-at="2022-09-07T12:32:47 IST" name="Default Suite" finished-at="2022-09-07T12:32:52 IST" duration-ms="5401">
    <groups>
    </groups>
    <test started-at="2022-09-07T12:32:47 IST" name="APIAutomation" finished-at="2022-09-07T12:32:52 IST" duration-ms="5401">
      <class name="com.excelr.test.PetShopTest">
        <test-method signature="getPetDetailByIdTest()[pri:0, instance:com.excelr.test.PetShopTest@a1153bc]" started-at="2022-09-07T12:32:47 IST" name="getPetDetailByIdTest" finished-at="2022-09-07T12:32:52 IST" duration-ms="5295" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.excelr.test.PetShopTest.getPetDetailByIdTest(PetShopTest.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[{"id":901,"category":{"id":0,"name":"string"},"name":"doggie-901","photoUrls":["string"],"tags":[{"id":0,"name":"string"}],"status":"available"}]]>
            </line>
          </reporter-output>
        </test-method> <!-- getPetDetailByIdTest -->
      </class> <!-- com.excelr.test.PetShopTest -->
    </test> <!-- APIAutomation -->
  </suite> <!-- Default Suite -->
</testng-results>
